refactor: script to include error messages

diff --git a/.github/workflows/post-usage.yml b/.github/workflows/post-usage.yml
--- a/.github/workflows/post-usage.yml
+++ b/.github/workflows/post-usage.yml
@@ -26,8 +26,13 @@ jobs:
           -H "Accept: application/vnd.github.v3+json" "$API_URL")
 
           # Log messages if API failure is observed
-          if [[ "$api_response" -ne 200 && "$api_response" -ne 201 ]]; then
-            echo "Error: Received HTTP status $api_response while checking team membership"
+          if [[ "$api_response" -eq 404 ]];then
+            echo "======================"
+            echo "Error: User not found"
+            echo "======================"
+            exit 1
+          elif [[ "$api_response" -ne 200 && "$api_response" -ne 201 ]]; then
+            echo "Error: Received HTTP status $api_response while checking team membership!"
             echo "======================"
             cat response_body.json
             echo "======================"
