fix: add debug and trim comment

diff --git a/.github/workflows/post-usage.yml b/.github/workflows/post-usage.yml
--- a/.github/workflows/post-usage.yml
+++ b/.github/workflows/post-usage.yml
@@ -9,22 +9,43 @@ on:
 jobs:
   Notify-Contributor-Requirements:
     runs-on: ubuntu-latest
-    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' }}
+    if: ${{ github.event.issue.pull_request && (trim(github.event.comment.body) == '/run pipeline') }}
     steps:
       - name: Check Team Membership
         id: check_team
         run: |
-          user_in_team=$(curl -X GET -H "Authorization: Bearer ${{secrets.ORG_READER_GH_TOKEN}}" \
+          set -e
+          response=$(curl -X GET -H "Authorization: Bearer ${{secrets.ORG_READER_GH_TOKEN}}" \
           -H "Accept: application/vnd.github.v3+json" \
-          "https://api.github.com/orgs/${{github.event.organization.login}}/teams/${{inputs.required_team}}/memberships/${{github.actor}}" | jq -r '.state')
+          -w "%{http_code}" \
+          -o response_body.json \
+          "https://api.github.com/orgs/${{github.event.organization.login}}/teams/${{inputs.required_team}}/memberships/${{github.actor}}")
+
+          if [[ "$response" -ne 200 ]]; then
+            echo "Error: Received HTTP status $response"
+            cat response_body.json
+            exit 1
+          fi
+
+          user_in_team=$(jq -r '.state' response_body.json)
           echo "user_in_team=$user_in_team" >> $GITHUB_ENV
 
       - name: Post Comment and stop workflow if user is not a member
         run: |
+          set -e
           if [[ "${{ env.user_in_team }}" != "active" ]]; then
-            curl -X POST -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
+            response=$(curl -X POST -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
             -H "Accept: application/vnd.github.v3+json" \
+            -w "%{http_code}" \
+            -o response_body_comment.json \
             https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}}/comments \
-            -d "{\"body\": \"@${{github.actor}} you must be in the team **[${{inputs.required_team}}](https://github.com/orgs/${{github.event.organization.login}}/teams/${{inputs.required_team}})** in order to trigger the pipeline.\"}"
+            -d "{\"body\": \"@${{github.actor}} you must be in the team **[${{inputs.required_team}}](https://github.com/orgs/${{github.event.organization.login}}/teams/${{inputs.required_team}})** in order to trigger the pipeline.\"}")
+
+            if [[ "$response" -ne 201 ]]; then
+              echo "Error: Received HTTP status $response while posting comment"
+              cat response_body_comment.json
+              exit 1
+            fi
+
             exit 1
           fi
