feat: exposed the ability to pass `TOOLCHAIN_ID` in cra-config.yaml (#635)

diff --git a/.github/workflows/terraform-test-pipeline.yml b/.github/workflows/terraform-test-pipeline.yml
--- a/.github/workflows/terraform-test-pipeline.yml
+++ b/.github/workflows/terraform-test-pipeline.yml
@@ -137,6 +137,20 @@ jobs:
                   echo "CRA_TARGET ${CRA_TARGET} set from config file ${{ inputs.craConfigYamlFile }}"
                 fi
 
+                ENV_TOOLCHAIN_ID=${TOOLCHAIN_ID}
+                TOOLCHAIN_ID=$(yq e ".CRA_TARGETS[$i].TOOLCHAIN_ID | select (.!=null)" "${{ inputs.craConfigYamlFile }}")
+                if [[ -z "${TOOLCHAIN_ID}" ]]; then
+                  TOOLCHAIN_ID="${ENV_TOOLCHAIN_ID}"
+                  if [[ -z "${TOOLCHAIN_ID}" ]]; then
+                    echo "Error: No TOOLCHAIN_ID specified in the YAML config or as an environment variable."
+                    exit 1
+                  else
+                    echo "TOOLCHAIN_ID ${TOOLCHAIN_ID} set from environment variable"
+                  fi
+                else
+                  echo "TOOLCHAIN_ID ${TOOLCHAIN_ID} set from config file ${{ inputs.craConfigYamlFile }}"
+                fi
+
                 CRA_IGNORE_RULES_FILE=$(yq e ".CRA_TARGETS[$i].CRA_IGNORE_RULES_FILE | select (.!=null)" "${{ inputs.craConfigYamlFile }}")
                 # get full path to ignore file from root of the repo
                 if [[ -n "${CRA_IGNORE_RULES_FILE}" ]]; then
